#ifndef CONFIG_H_INCLUDED
#define CONFIG_H_INCLUDED

#define PORT 8080
#define RECEIVEBUFSIZE 1024


// DOCKER COMPOSE OR INDIVIDUAL - Use according IP-Adress
#define DOCKERCOMPOSE
#ifdef DOCKERCOMPOSE
    #define CONTROLUNIT_IPADDR "172.20.128.4"
#else
    #define CONTROLUNIT_IPADDR "172.17.0.4"
#endif // DOCKERCOMPOSE


#endif // CONFIG_H_INCLUDED